### ISSUE TITLE
Thuật toán chưa ổn định

### ISSUE THREAD

**Issue by dungwinux** [Amaterasu-Oomikami/Sudoku#1]
- Thuật toán sinh map Sudoku chưa ổn định, có lúc khó, có lúc dễ. Thuật toán cần được cải thiện. @Amaterasu-Oomikami 
![image](https://user-images.githubusercontent.com/23451424/59014930-0007d380-8868-11e9-9224-0a65f79d965c.png)

**Comment by t41y0u** [comment]
Em đã (cố) sửa lại thuật toán

**Comment by t41y0u** [comment]
Thuật toán đã được sửa cho thành tương đối ổn định
